### ISSUE TITLE
Should I concentrate on CSS?

### ISSUE THREAD

**Issue by srinivasdamam** [hemanth/ama#38]
I love JavaScript. I hate CSS, I have very bad design sense. This is letting my confidence down every time. Being a JS developer, should I really care about CSS?

**Comment by hemanth** [comment]
![image](https://cloud.githubusercontent.com/assets/18315/17843164/7ff3ece8-6848-11e6-98e8-1574df5cc67d.png)


That being said, even if you design sense is bad, it would be a good move in implementing others design, doing away with CSS and focusing only on CSS wouldn't be a good idea, unless you just need to focus on being a server side dev, rather than a full stack JavaScript dev.
